services:
  sirius-ui:
    build:
      context: ./sirius-ui
      dockerfile: Dockerfile
      target: production # Use production stage
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - SIRIUS_API_URL=${SIRIUS_API_URL}
      - NEXT_PUBLIC_SIRIUS_API_URL=${NEXT_PUBLIC_SIRIUS_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - sirius-postgres
    restart: unless-stopped
    # No volumes in production - use built image as-is
