version: "3.9"

services:
  mongo:
    command: mongod --quiet --logpath /dev/null
    image: mongo
    restart: always
    ports:
      - 27017:27017

  #  rabbitmq:
  #    image: rabbitmq:3-management
  #    restart: always
  #    logging:
  #      driver: none
  #    ports:
  #      - 5672:5672
  #      - 15672:15672
  #    volumes:
  #      - ./rabbit-mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
  #    healthcheck:
  #      test: ["CMD", "rabbitmqctl", "status"]
  #      interval: 30s
  #      timeout: 15s
  #      retries: 5

  # sirius-api:
  #   build: ./sirius-api/
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./sirius-api:/api
  #   depends_on:
  #     - mongo
  #     - rabbitmq

  sirius-ui:
    build:
      context: ./sirius-ui/
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./sirius-ui:/app
      - /ui/node_modules
#  sirius-engine:
#    build: ./sirius-engine/
#    restart: always
#    ports:
#      - "5174:5174"
#    volumes:
#      - ./sirius-engine:/engine
#    depends_on:
#      - rabbitmq
