name: sirius

services:
  sirius-rabbitmq:
    image: rabbitmq:3.7.3-management
    restart: always
    container_name: sirius-rabbitmq
    hostname: sirius-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
       - ./rabbit-mq/rabbitmq.conf:/etc/rabbitmq.conf:ro
    healthcheck:
       test: ["CMD", "rabbitmqctl", "status"]
       interval: 30s
       timeout: 15s
       retries: 5

  sirius-libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    restart: always
    container_name: sirius-libsql
    hostname: sirius-libsql
    ports:
      - "9010:8080"

  sirius-valkey:
    image: valkey/valkey:latest
    restart: always
    container_name: sirius-valkey
    hostname: sirius-valkey
    ports:
      - "6379:6379"

  sirius-ui:
    build:
      context: ./sirius-ui/
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    container_name: sirius-ui
    hostname: sirius-ui
    restart: always
    image: sirius-ui
    working_dir: /app
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./sirius-ui:/app
      - /app/node_modules

  sirius-api:
    build: ./sirius-api/
    container_name: sirius-api
    hostname: sirius-api
    restart: always
    image: sirius-api
    ports:
      - "9001:9001"
    volumes:
      - ./sirius-api:/api
      - ../minor-projects/go-api:/go-api # Local Development

  sirius-engine:
    build: ./sirius-engine/
    container_name: sirius-engine
    hostname: sirius-engine
    restart: always
    image: sirius-engine
    ports:
      - "5174:5174"
    volumes:
      - ./sirius-engine:/engine
      - ../minor-projects/go-api:/go-api # Local Development
      - ../minor-projects/app-scanner:/app-scanner # Local Development
      - ../minor-projects/app-terminal:/app-terminal # Local Development
    # depends_on:
    #   - rabbitmq
