version: '3.4'
services:
  mongo:
    vscommand: mongod --quiet --logpath /dev/null 
    image: mongo
    restart: always
    ports:
      - 27017:27017

  sirius-api:
    build: ./API/
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./API:/api
    depends_on:
      - mongo

  sirius-web:
    build: ./UI/
    ports:
      - "5173:5173"
    volumes:
      - ./UI:/app
    depends_on:
      - sirius-api